// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpixlchyybzvybokyarx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwaXhsY2h5eWJ6dnlib2t5YXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDI5OTEsImV4cCI6MjA3MTAxODk5MX0.5bEuNktAF8C9bfRyftRmhfqY_O-pzehXUg0JSofgJ6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});